apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/NgocLe-101/spring-petclinic-helm-charts.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - dev/values/admin-server-values.yaml
        - dev/values/api-gateway-values.yaml
        - dev/values/config-server-values.yaml
        - dev/values/discovery-server-values.yaml
        - dev/values/customers-service-values.yaml
        - dev/values/vets-service-values.yaml
        - dev/values/visits-service-values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true