apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: prometheus-server
  type: "ClusterIP"
  ports:
  - protocol: TCP
    port: {{ .Values.prometheus.service.port | default 9090 }}
    targetPort: {{ .Values.prometheus.service.port | default 9090 }}
    {{- if eq .Values.prometheus.service.type "NodePort" }}
    nodePort: {{ .Values.prometheus.service.nodePort | default 30090 }}
    {{- end }}
  type: {{ .Values.prometheus.service.type | default "ClusterIP" }}
