apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.serviceName }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.servicePort }}
    targetPort: {{ .Values.service.servicePort }}
---

