{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $svc.deployment.serviceName }}
  type: {{ $svc.service.type | default "ClusterIP" }}
  ports:
  - name: http
    protocol: TCP
    port: {{ $svc.service.servicePort }}
    targetPort: {{ $svc.service.servicePort }}
{{- end }}
